apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  nodeSelector:
        kubernetes.io/hostname: instance-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi