apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
        track: stable
    spec:
      nodeSelector:
        kubernetes.io/hostname: instance-1
      containers:
        - name: mongo
          image: "akshaysood112/mongo:v2"
          ports:
            - name: mongoport
              containerPort: 27017
          command: ["mongod"]
