apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
        track: stable
    spec:
      containers:
        - name: mongo
          image: "akshaysood112/mongo:v2"
          ports:
            - name: mongoport
              containerPort: 27017
          command: ["mongod"]
          volumeMounts:
            - name: mongo-persistence-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistence-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
