apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-test
  template:
    metadata:
      labels:
        app: express-test
        tier: backend
        track: stable
    spec:
      nodeSelector:
        kubernetes.io/hostname: instance-2
      containers:
        - name: express-test
          image: "akshaysood112/express-sample:v2"
          ports:
            - name: expressport
              containerPort: 3000
          command: ["npm","start"]
