apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-test
  template:
    metadata:
      labels:
        app: express-test
        tier: backend
        track: stable
    spec:
      containers:
        - name: express-test
          image: "akshaysood112/express-sample:v2"
          ports:
            - name: expressport
              containerPort: 3000
          command: ["npm","start"]
        - name: mongo
          image: "akshaysood112/mongo:v2"
          ports:
            - name: mongoport
              containerPort: 27017
          command: ["mongod"]
          volumeMounts:
            - name: mongo-persistence-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistence-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
